  image: docker:latest
  services:
    - docker:dind
  stages: 
    - build
    - deploy
  variables:
    REPOSITORY_URL: $DOCKER_REGISTRY/$APP_NAME
    TASK_DEFINITION_NAME: <Task_Definition>
    CLUSTER_NAME: <CLUSTER_NAME>
    SERVICE_NAME: <SERVICE_NAME>  
  before_script:
        - apk add --no-cache curl jq python3 py3-pip
        - pip install awscli
        - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
        - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"
  build:
    stage: build
    script:
        - echo "Building image..."
        - docker build -t $REPOSITORY_URL:latest APITest02
        - echo "Tagging image..."
        - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG
        - echo "Pushing image..."
        - docker push $REPOSITORY_URL:$IMAGE_TAG
    only:
        - main
        - develop
  #deploy:
    #stage: deploy
    #script:
    #    - echo $REPOSITORY_URL:$IMAGE_TAG
    #    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_DEFINITION_NAME" --region "${AWS_DEFAULT_REGION}")
    #    - NEW_CONTAINER_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$REPOSITORY_URL:$IMAGE_TAG" '.taskDefinition.containerDefinitions[0].image = $IMAGE | .taskDefinition.containerDefinitions[0]')
    #    - echo "Registering new container definition..."
    #    - aws ecs register-task-definition --region "${AWS_DEFAULT_REGION}" --family "${TASK_DEFINITION_NAME}" --container-definitions "${NEW_CONTAINER_DEFINTIION}"
    #    - echo "Updating the service..."
    #    - aws ecs update-service --region "${AWS_DEFAULT_REGION}" --cluster "${CLUSTER_NAME}" --service "${SERVICE_NAME}" --task-definition "${TASK_DEFINITION_NAME}"
   # only:
    #- main
