CLIENTS:
PK Name: "STRING" // BARCLAYS EXECUTION SERVICES LIMITED
SK ID: "STRING", // Barclays

DEMAND:
PK Client": ['ClientId'], // Barclays
SK CreationDate: "STRING", // Date
   Skills: ['SkillName']
   StartDate: "STRING", // Date
   CodeRequisition: "INT", // 12200345
   Grade: "STRING", // B2
   Location: "STRING", // London
   Notes: "STRING", // Notes
   OriginatorName: "STRING", // Ben 
   Probability: "STRING", // null
   ProposedApplicant: "STRING", // Ben
   SelectedApplicant: "STRING", ['Supply'] // Steve 
   Status: "STRING" // Pending

SKILLS:
PK Name: "STRING", // React
SK Priority: "INT", // 1

SUPPLY":
PK ID: 'Int'
SK Skills": ['SkillName']
SK? Status": "STRING", // Offered
   FirstName: "STRING", // Ben
   LastName": "STRING", // More
   Type": "STRING", // External Hire
   Location": "STRING", // London
   Notes: "STRING", // Notes

USERS":
PK Username": "STRING" // Ben
SK Role: "STRING", // admin
   Password: "STRING", // g67y6f7f